### ISSUE TITLE
fix .jpg file extension

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-owa#1]
some of the img file extensions are capitalized, and are not being recognized when served over the web. just change them to lower case.

here's what you need to fix: 

![jpg-fix](https://cloud.githubusercontent.com/assets/539962/7699864/b49cbc66-fdcf-11e4-908c-00255e0bb424.jpg)

**Comment by purplyrocky** [comment]
@rodneystrong This is so weird, I tried a couple things to fix this but they did not work.  I will keep trying when I come in today.

**Comment by rodneystrong** [comment]
@purplyrocky no biggie, all you gotta do is just change it from .JPG to .jpg. Then just do the usual 'git add .' and 'git commit -m' and 'git push'.

**Comment by purplyrocky** [comment]
fixed file extensions with this commit: 92454c2221eb075dfda8c0d147ab93ad568042af

removed images with .JPG with this one: 4ec3a4ec2cae624c46e310e788953000e366c266
